config/routes.rb
Rails.application.routes.draw do

  root to:'homes#index'

  resources :recipes
  
  resources :films
  
  resources :films do
    resources :sections
  end

  resources :companies
  resources :people
  resources :songlists
  
  resources :user_sessions
  resources :users



  # get replaces match
  get 'login', :to => 'user_sessions#new', :as => 'login'
  get 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  get 'register/:activation_code', :to => 'activations#new', :as => 'register'
  match 'activate/:id', :to => 'activations#create', :as => 'activate', via: [:get, :post]
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/film.rb
class Film < ApplicationRecord
  has_one_attached :image
  
  has_many :sections
  has_many :filmers
  has_many :people_filmers, through: :filmers, source: :person
  
  has_many :editors
  has_many :people_editors, through: :editors, source: :person
  
  has_many :filmcompanies
  has_many :film_companies, through: :filmcompanies, source: :company
  
  def to_param
    "#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}"
  end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]
  
  filter_resource_access

  # GET /films
  def index
    if params[:letter].blank?
      @pagy_az, @films_az = pagy(Film.order(:name).where("draft = ?", 0), page_param: :page_az, params: { active_tab: 'az' })
    elsif params[:letter] == '#'
      @pagy_az, @films_az = pagy(Film.order(:name).where("name REGEXP ? and draft = ?",
      "^[^a-z]", 0).order('name'), page_param: :page_az, params: { active_tab: 'az' })
    else
      @pagy_az, @films_az = pagy(Film.order(:name).where("name like ? and draft = ?",
      "#{params[:letter]}%", 0).order('name'), page_param: :page_az, params: { active_tab: 'az' })
    end
    
    
    if params[:type].blank?
      @pagy_years, @films_year = pagy(Film.order(:release_year), page_years: :page_nebulae, params: { active_tab: 'years' })
    elsif params[:type] == 'year'
      if params[:start].blank? || params[:end].blank?
        @pagy_years, @films_year = pagy(Film.order(:release_year).where("release_year IS NULL AND draft = 0"), page_years: :page_nebulae, params: { active_tab: 'years' })
      else
        @pagy_years, @films_year = pagy(Film.order(:release_year).where("release_year between " + params[:start] +
                                   " and " + params[:end] + " and draft = 0"), page_years: :page_nebulae, params: { active_tab: 'years' })
      end
    end

    
  end
  
  # GET /films/1
  def show
  end
  
  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      # params.fetch(:film, {})
      params.require(:film).permit(:name,
                                   :format_web,
                                   :format_dvd,
                                   :format_vhs,
                                   :format_blu,
                                   :country,
                                   :runtime,
                                   :notes,
                                   :release_year,
                                   :user_id,
                                   :draft,
                                   :locked,
                                   :image)
    end
end

app/helpers/films_helper.rb
module FilmsHelper
    # moved to application_helper, here for illustration purposes
    # def letter_options
    #     $letter_options_list ||= ['#'].concat(("A".."Z").to_a)
    # end

    # don't think this is the best way, maybe array of link_to, so I can apply styles dynamically
    def year_options
         link_to('Unknown', :type => 'year', :active_tab => 'years') + 
         link_to('1980-1989', :type => 'year', :start => 1980, :end => 1989, :active_tab => 'years') + 
         link_to('1990-1999', :type => 'year', :start => 1990, :end => 1999, :active_tab => 'years') + 
	     link_to('2000-2009', :type => 'year', :start => 2000, :end => 2009, :active_tab => 'years') + 
	     link_to('2010-', :type => 'year', :start => 2010, :end => 2100, :active_tab => 'years')
    end

    def formats(film)
        rtn = []
        if film.format_vhs
            rtn.push("VHS")
        end
        if film.format_dvd
            rtn.push("DVD")
        end
        if film.format_web 
            rtn.push("Web")
        end
        if film.format_blu
            rtn.push("Blu Ray")
        end
        rtn.join(' | ')
    end
end

app/views/films/_form.html.erb
<%= form_with(model: @film, local: true) do |form| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', recipe: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link <%= 'active' unless params[:active_tab] == 'years' %>" aria-controls="az" data-toggle="tab" href="#az" role="tab">
      A - Z
    </a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link <%= 'active' if params[:active_tab] == 'years' %>" aria-controls="years" data-toggle="tab" href="#years" role="tab">
      Years
    </a>
  </li>
</ul>

<div class="tab-content">
  <div class="tab-pane <%= 'active' unless params[:active_tab] == 'years' %>" id="az">
    <h2 class="mt-3 mb-2">A - Z</h2>
    <div>
      <% letter_options.each do |letter| %>
        <% if params[:letter] == letter %>
          <span class="current"><%= letter %></span>
        <% else %>
          <%= link_to letter, films_path(:letter => letter, :active_tab => 'az')%>
        <% end %>
      <% end %>
    </div>
    <table class="table">
      
      <% @films_az.each do |film| %>
        <tr>
          <td><%= link_to film.name, film_path(film) %></td>
        </tr>
      <% end %>
    </table>
    <%== pagy_nav_compact_bootstrap @pagy_az %>
  </div>

  <div class="tab-pane <%= 'active' if params[:active_tab] == 'years' %>" id="years">
    <h2 class="mt-3 mb-2">Years</h2>

    <%= year_options %>

    <table class="table">

    
      
      <% @films_year.each do |film| %>
        <tr>
          <td><%= film.name %></td>
        </tr>
      <% end %>
    </table>
    <%== pagy_nav_compact_bootstrap @pagy_years %>
  </div>
</div>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
    
    <div class="row">

      <div class="col-sm-9 mb-2">

          <div class="jumbotron">
            <h1 class="display-4"><%= @film.name %><%= film_release(@film)%></h1>
            <p class="lead"><%= film_information(@film) %></p>
            <p><%= @film.notes %></p>
            
              <% @film.film_companies.each do |company| %>
                      <% if company.company_logo.attached? %>
                          <%= link_to image_tag(company.company_logo.variant(resize: '80x')), company %></li>
                        <% else %>
                          <%= link_to company.name, company %>
                      <% end %>
              <% end %>
            
          </div>
        
        <% unless @film.people_editors.empty? %>
          <div class="ml-2 pl-4"><%= "Editor".pluralize(@film.people_editors.count) %></div>
          <ul class="list-unstyled ml-2 pl-4">
          <% @film.people_editors.each do |editor| %>
                  <li><%= link_to editor.name,  editor %></li>
          <% end %>
          </ul>
        <% end %>

        <% unless @film.people_filmers.empty? %>
          <div class="ml-2 pl-4"><%= "Filmer".pluralize(@film.people_filmers.count) %></div>
          <ul class="list-unstyled ml-2 pl-4">
          <% @film.people_filmers.each do |filmer| %>
                  <li><%= link_to filmer.name,  filmer %></li>
          <% end %>
          </ul>
        <% end %>

        


      </div>

      <div class="col-sm-3 mb-2">
        <% if @film.image.attached? %>
          <%= link_to @film.image, data: { toggle: 'lightbox'} do
                image_tag @film.image.variant(resize: '200x')      
          end %>
        <% end %>
      </div>

    </div>
  
  

  


</div>





<div class="row">
  
<% @film.sections.order(:id).map do | section | %>
      <div class="col-sm-6 mb-4">
        <%= render partial: "shared/film_section", object: section %>
      </div>

      <div class="col-sm-6 mb-4">
        <%= render partial: "shared/section_info", object: section %>
      </div>
<% end  %>

</div>


<%= render partial: "shared/modal_carousel", object: @film.sections %>

</div>