config/routes.rb
Rails.application.routes.draw do

  root to:'homes#index'

  resources :recipes
  
  resources :films
  
  resources :films do
    resources :sections
  end

  resources :companies
  resources :people
  resources :songlists
  
  resources :user_sessions
  resources :users



  # get replaces match
  get 'login', :to => 'user_sessions#new', :as => 'login'
  get 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  get 'register/:activation_code', :to => 'activations#new', :as => 'register'
  match 'activate/:id', :to => 'activations#create', :as => 'activate', via: [:get, :post]
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_one_attached :company_logo

  has_many :filmcompanies
  has_many :films, through: :filmcompanies
  
  def to_param
    "#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    before_action :set_company, only: [:show, :edit, :update, :destroy]

    def index
        if params[:letter].blank?
            @pagy_az, @companies = pagy(Company.order(:name), page_param: :page_az, params: { active_tab: 'az' })
        elsif params[:letter] == '#'
            @pagy_az, @companies = pagy(Company.order(:name).where("name REGEXP ?", 
            "^[^a-z]").order('name'), page_param: :page_az, params: { active_tab: 'az' })
        else
            @pagy_az, @companies = pagy(Company.order(:name).where("name like ?",
            "#{params[:letter]}%").order('name'), page_param: :page_az, params: { active_tab: 'az' })
        end
    end

    # GET /companies/1
    def show
    end
    
    # GET /companies/new
    def new
        @company = Company.new
    end

    # GET /companies/1/edit
    def edit
    end

    # POST /companies
    # POST /companies.json
    def create
        @company = Company.new(company_params)

        respond_to do |format|
        if @company.save
            format.html { redirect_to @company, notice: 'Company was successfully created.' }
            format.json { render :show, status: :created, location: @company }
        else
            format.html { render :new }
            format.json { render json: @company.errors, status: :unprocessable_entity }
        end
        end
    end

    # PATCH/PUT /companies/1
    # PATCH/PUT /companies/1.json
    def update
        respond_to do |format|
        if @company.update(company_params)
            format.html { redirect_to @company, notice: 'Company was successfully updated.' }
            format.json { render :show, status: :ok, location: @company }
        else
            format.html { render :edit }
            format.json { render json: @company.errors, status: :unprocessable_entity }
        end
        end
    end

    # DELETE /companies/1
    # DELETE /companies/1.json
    def destroy
        @company.destroy
        respond_to do |format|
        format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
        format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :company_logo)
    end
end

app/views/companies/_form.html.erb
<%= form_with(model: @company, local: true) do |form| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :company_logo %>
    <%= form.file_field :company_logo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', recipe: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
  <ul class="nav nav-tabs" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link <%= 'active'  %>" aria-controls="az" data-toggle="tab" href="#az" role="tab">
      A - Z
    </a>
  </li>
  </ul>

  <div class="tab-content">
  <div class="tab-pane <%= 'active' unless params[:active_tab] == 'years' %>" id="az">
    <h2 class="mt-3 mb-2">A - Z</h2>
    <div>
      <% letter_options.each do |letter| %>
        <% if params[:letter] == letter %>
          <span class="current"><%= letter %></span>
        <% else %>
          <%= link_to letter, companies_path(:letter => letter, :active_tab => 'az')%>
        <% end %>
      <% end %>
    </div>
    <table class="table">
      
      <% @companies.each do |company| %>
        <tr>
          <td><%= link_to company.name, company_path(company) %></td>
        </tr>
      <% end %>
    </table>
    <%== pagy_nav_compact_bootstrap @pagy_az %>
  </div>
</div>

app/views/companies/show.html.erb
<div class="container-fluid">

<h2><%= @company.name %></h2>

<% if @company.company_logo.attached? %>
  <p>
    <%= image_tag @company.company_logo %>
  </p>
<% end %>


<% @company.films.order("release_year").each_slice(3) do |films| %>
  
  <%= render partial: "shared/film_card", object: films %>

<% end %>


</div>