config/routes.rb
Rails.application.routes.draw do

  root to:'homes#index'

  resources :recipes
  
  resources :films
  
  resources :films do
    resources :sections
  end

  resources :companies
  resources :people
  resources :songlists
  
  resources :user_sessions
  resources :users



  # get replaces match
  get 'login', :to => 'user_sessions#new', :as => 'login'
  get 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  get 'register/:activation_code', :to => 'activations#new', :as => 'register'
  match 'activate/:id', :to => 'activations#create', :as => 'activate', via: [:get, :post]
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    belongs_to :user
    belongs_to :role
  end

app/models/company.rb
class Company < ApplicationRecord
  has_one_attached :company_logo

  has_many :filmcompanies
  has_many :films, through: :filmcompanies
  
  def to_param
    "#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}"
  end
end

app/models/editor.rb
class Editor < ApplicationRecord
  belongs_to :film
  belongs_to :person
  
end

app/models/film.rb
class Film < ApplicationRecord
  has_one_attached :image
  
  has_many :sections
  has_many :filmers
  has_many :people_filmers, through: :filmers, source: :person
  
  has_many :editors
  has_many :people_editors, through: :editors, source: :person
  
  has_many :filmcompanies
  has_many :film_companies, through: :filmcompanies, source: :company
  
  def to_param
    "#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}"
  end

end

app/models/filmcompany.rb
class Filmcompany < ApplicationRecord
  belongs_to :film
  belongs_to :company
  
end

app/models/filmer.rb
class Filmer < ApplicationRecord
  belongs_to :film
  belongs_to :person
  
end

app/models/home.rb
class Home < AppplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :filmers
  has_many :film_filmers, through: :filmers, source: :film
  
  has_many :editors
  has_many :film_editors, through: :editors, source: :film

  has_many :riders
  has_many :sections, through: :riders
  
  def to_param
    "#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}"
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/rider.rb
class Rider < ApplicationRecord
  belongs_to :section
  belongs_to :person
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :assignments
    has_many :users, :through => :assignments
  end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :film
  
  has_many :riders
  has_many :people_riders, through: :riders, source: :person
  
  has_many :songs
  has_many :section_songs, through: :songs, source: :songlist
  
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :section
  belongs_to :songlist
end

app/models/songlist.rb
class Songlist < ApplicationRecord
  has_many :songs
  has_many :sections, through: :songs
  
  def to_param
    "#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}-#{artist.gsub(/[^a-z0-9]+/i, '-')}"
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :films
    has_many :assignments
    has_many :roles, :through => :assignments

    

    acts_as_authentic do |c|
        # c.crypto_provider = Authlogic::CryptoProviders::Sha512

        # FIX should use the below to transfer users to new CryptoProvider
        c.transition_from_crypto_providers = [Authlogic::CryptoProviders::Sha512]
        c.crypto_provider = Authlogic::CryptoProviders::SCrypt
        c.validate_password_field = false
    end

      # attr_accessible :username, :email, :password, :password_confirmation
    
      def allowed_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
      end 



    validates :email,
    format: {
      with: /@/,
      message: "should look like an email address."
    },
    length: { maximum: 100 },
    uniqueness: {
      case_sensitive: false,
      if: :will_save_change_to_email?
    }

  validates :username,
    format: {
      with: /\A[a-z0-9]+\z/,
      message: "should use only letters and numbers."
    },
    length: { within: 4..100 },
    uniqueness: {
      case_sensitive: false,
      if: :will_save_change_to_username?
    }

  # validates :password,
  #   confirmation: { if: :require_password? },
  #   length: {
  #     minimum: 8,
  #     if: :require_password?
  #   }
  # validates :password_confirmation,
  #   length: {
  #     minimum: 8,
  #     if: :require_password?
  # }

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def active?
    active
  end

  def activate!
    self.active = true
    save
  end
  
  def has_no_credentials?
    self.crypted_password.blank?
  end

  def signup!(params)
    self.username = params[:username]
    self.email = params[:email]
  end

  def activate!(params)
    self.active = true
    self.password = params[:user][:password]
    # self.password_confirmation = params[:user][:password_confirmation]
    save
  end


end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
    
end

app/helpers/application_helper.rb
module ApplicationHelper

    include Pagy::Frontend

    def letter_options
        $letter_options_list ||= ['#'].concat(("A".."Z").to_a)
    end

    def thumb_image_tag(section_url)
        if section_url != ""
            image_tag(section_url, class: "img-responsive")
        end
    end

    def film_information(film)
        rtn = []
        if film.runtime.present?
            rtn.append(film.runtime)
        end
        rtn.append(formats(film))
        if film.country.present?
            rtn.append(film.country)
        end
        rtn.join(' | ')
    end

    def film_release(film)
        rtn = ""
        if film.release_year.present?
            rtn = "<small class='text-muted'>(#{film.release_year})</small>".html_safe 
        end
    end
end

app/helpers/films_helper.rb
module FilmsHelper
    # moved to application_helper, here for illustration purposes
    # def letter_options
    #     $letter_options_list ||= ['#'].concat(("A".."Z").to_a)
    # end

    # don't think this is the best way, maybe array of link_to, so I can apply styles dynamically
    def year_options
         link_to('Unknown', :type => 'year', :active_tab => 'years') + 
         link_to('1980-1989', :type => 'year', :start => 1980, :end => 1989, :active_tab => 'years') + 
         link_to('1990-1999', :type => 'year', :start => 1990, :end => 1999, :active_tab => 'years') + 
	     link_to('2000-2009', :type => 'year', :start => 2000, :end => 2009, :active_tab => 'years') + 
	     link_to('2010-', :type => 'year', :start => 2010, :end => 2100, :active_tab => 'years')
    end

    def formats(film)
        rtn = []
        if film.format_vhs
            rtn.push("VHS")
        end
        if film.format_dvd
            rtn.push("DVD")
        end
        if film.format_web 
            rtn.push("Web")
        end
        if film.format_blu
            rtn.push("Blu Ray")
        end
        rtn.join(' | ')
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_navigation.html.erb
<div class="container">
<nav class="navbar navbar-expand-lg navbar-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= link_to "BMX Movie Database", root_path, class: 'navbar-brand' %>
    <ul class="navbar-nav mr-auto">
      <%= render 'layouts/navigation_links' %>
    </ul>
    <div class="mr-sm-0">
      <% if current_user %>
        <%= current_user.username %>&nbsp;|&nbsp;<%= link_to "Logout", logout_path %>
      <% else %>
        <%= link_to "Login", login_path %>&nbsp;|&nbsp;<%= link_to "Register", new_user_path %>
      <% end %>
    </div>
    
  </div>
</nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'Films', films_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Companies', companies_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'People', people_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Songs', songlists_path, class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BMX Movie Database</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

    <header>
      <%= render 'layouts/navigation' %>
    </header>
    
        <div class="bg"></div>
    <main role="main">
       <%= yield %>
    </main>

  </body>
</html>

app/views/shared/_film_card.html.erb
<div class="row justify-content-start">
  <% film_card.each do |film| %>
        <div class="col-md-4 d-flex">
        <%= link_to(film) do %>
          <div class="card mb-4">
          <p>
            <% if film.image.attached? %>
              <%= image_tag film.image, :class => "card-img-top img-fluid" %>
            <% else %>
              <% if formats(film).include? "VHS" %>
                <%= image_tag 'vhs_case.png' , :class => "card-img-top img-fluid" %>
              <% else %>
                <%= image_tag 'dvd_case.png' , :class => "card-img-top img-fluid" %>
              <% end %>
            <% end %>
          </p>
        <div class="card-body flex-fill">
          <h5 class="card-title"><%= film.name %></h5>
          <p class="card-text">
          <span><%= film.release_year %></span>
          <span><%= formats(film) %></span>
          <span><%= film.country %></span>
          </p>
        </div>
      </div>
      <% end %>
      </div>
  <% end %>
</div>

app/views/shared/_film_mini_card.html.erb
<div class="row justify-content-start">
  <% film_mini_card.each do |film| %>
        <div class="col-md-2 d-flex">
        <%= link_to(film) do %>
          <div class="card mb-2 h-100">
          <p>
            <% if film.image.attached? %>
              <%= image_tag film.image, :class => "card-img-top img-fluid" %>
            <% else %>
              <% if formats(film).include? "VHS" %>
                <%= image_tag 'vhs_case.png' , :class => "card-img-top img-fluid" %>
              <% else %>
                <%= image_tag 'dvd_case.png' , :class => "card-img-top img-fluid" %>
              <% end %>
            <% end %>
          </p>
        <div class="card-body flex-fill">
          <h5 class="card-title"><%= film.name %></h5>
        </div>
      </div>
      <% end %>
      </div>
  <% end %>
</div>

app/views/shared/_film_section.html.erb
<div class="video-btn" data-toggle="modal" data-src="<%= get_autoplay_url(film_section.url) %>" 
              data-target="#myModal" data-video-fullscreen="1" data-section-name="<%= film_section.film.name %>&nbsp;(<%= film_section.name %>)">
    <div class="img-wrapper ml-4 pl-4"">
    <%= thumb_image_tag(get_thumbnail(film_section.url)) %>
        <div class="img-overlay">
            <div class=""><%= image_tag('playbutton.png') %></div>
        </div>
    </div>  
</div>

app/views/shared/_modal_carousel.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-body">

       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>        
        <!-- carousel -->
            <div id="sliderindicators" class="carousel slide" data-ride="carousel" data-interval="false">
                <div class="carousel-inner" role="listbox">
                    
                </div>
                    <a class="carousel-control-prev" href="#sliderindicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#sliderindicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
            </div>
        <!-- carousel -->
        
      </div>
        <div class="modal-footer">
            <div class="caption"></div>
        </div>
    </div>
  </div>
</div> 

app/views/shared/_section_card.html.erb
<div class="row justify-content-start">
    <% no_vid_array = [] %>
<% section_card.includes(:film).order("films.release_year").each do |section| %>
        
           <% unless section.film.draft == true %>
                <% if get_thumbnail(section.url) == "http://bmxmdb.com/images/film_preview.png" %>
                    <% no_vid_array.append(section) %>
                <% else %>
                    <div class="col-md-6 d-flex mb-2">
                        <div class="card mb-6">
                            <div class="video-btn" data-toggle="modal" data-src="<%= get_autoplay_url(section.url) %>" 
                                data-target="#myModal" data-video-fullscreen="1" data-section-name="<%= section.film.name %>&nbsp;(<%= section.name %>)">
                                <div class="img-wrapper">
                                <%= thumb_image_tag(get_thumbnail(section.url)) %>
                                    <div class="img-overlay">
                                        <div class=""><%= image_tag('playbutton.png') %></div>
                                    </div>
                                </div>  
                            </div>
                            
                        <div class="card-body flex-fill">
                            <h5 class="card-title"><%= link_to section.film.name, section.film %></h5>
                            <h6 class="card-title">(<%= section.name %>)</h6>
                            <p class="card-text">
                                <% section.film.film_companies.each do |company| %>
                                    <%= company.name %>
                                <% end %>
                                    
                            </p>
                        </div>
                    </div>
                </div> 
                <% end %>
            <% end %>
         
<% end %>
    </div>

<% unless no_vid_array.count != 0 %>   
<div class="row justify-content-start">
    <div class="col-md-6 d-flex mb-2">           
        <div class="card mb-6">      
            <div class="card-body mb-6">
                <h5 class="card-title">Sections without video</h5>
                <p class="card-text">
                    <ul>
                    <% no_vid_array.each do |novid| %>
                            <li><%= link_to novid.film.name + '(' +  novid.name + ')', novid.film %></li>
                    <% end %>
                    </ul>
                </p>
            </div>
        </div>
    </div> 
</div>
<% end %>

app/views/shared/_section_info.html.erb
<h4><%= section_info.name %></h4>
<div>
    <ul class="list-unstyled">
    <% section_info.people_riders.map do | rider | %>
        <li><%= link_to rider.name, rider %></li>
    <% end  %>
    </ul>
    <ul class="list-unstyled">
    <% section_info.section_songs.map do | song | %>
        <li><%= link_to (song.name + ' - ' +  song.artist), songlist_path(song.id) %></li>
    <% end  %>
    </ul>
</div>